[package]
name = "sooty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
serde_json = "1.0.108"
urlencoding = "2.1.3"
