on:
  push:
    tags:
      - v1.*
    branches:
      - main

jobs:
  setup_environment:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Package the environment
      run: |
        mkdir releases
        zip -r ./releases/SocPuppet.zip .
    - name: Upload the Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "SocPuppet"
        path: ./releases/SocPuppet.zip
