on:
  workflow_dispatch:
  push:
    tags:
      - v1.*
    branches:
      - main

jobs:
  setup_environment:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Remove unnecessary files
      run: |
        rm -rf .git
        rm -rf .github
        rm build.ps1
        rm SocPuppet.spec
        rm .gitignore
        rm CHANGELOG.md
        rm Dockerfile
    - name: Package the environment
      run: |
        mkdir releases
        zip -r ./releases/SocPuppet.zip .
    - name: Upload the Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "release"
        path: ./releases/SocPuppet.zip
